// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rules_Engine_API.Data;

#nullable disable

namespace Rules_Engine_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324225450_InitRulesEngine")]
    partial class InitRulesEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rules_Engine_API.Models.AttackEvaluationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ClassificationCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectionCorrect")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttackName");

                    b.HasIndex("EvaluationSessionId");

                    b.ToTable("AttackEvaluationRecords");
                });

            modelBuilder.Entity("Rules_Engine_API.Models.EvaluationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetectedAttackType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("bit");

                    b.Property<string>("MatchedAttacksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsEvaluated");

                    b.ToTable("EvaluationSessions");
                });

            modelBuilder.Entity("Rules_Engine_API.Models.AttackEvaluationRecord", b =>
                {
                    b.HasOne("Rules_Engine_API.Models.EvaluationSession", "EvaluationSession")
                        .WithMany("AttackEvaluations")
                        .HasForeignKey("EvaluationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationSession");
                });

            modelBuilder.Entity("Rules_Engine_API.Models.EvaluationSession", b =>
                {
                    b.Navigation("AttackEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
